
/* Drop Triggers */

DROP TRIGGER TRI_Exchange_T_exchange_type;
DROP TRIGGER TRI_HOUSE_T_KE_NO;
DROP TRIGGER TRI_K_TYPE_T_KE_TYPE;
DROP TRIGGER TRI_MEMO_T_ME_NO;
DROP TRIGGER TRI_PAY_T_PAY_TYPE;
DROP TRIGGER TRI_PAY_T_PAY_TYPE_NO;
DROP TRIGGER TRI_PROD_T_PROD_TYPE;
DROP TRIGGER TRI_SHOP_T_SHOP_NO;
DROP TRIGGER TRI_TODO_T_TOD_NO;



/* Drop Tables */

DROP TABLE HOUSE_T CASCADE CONSTRAINTS;
DROP TABLE SHOP_T CASCADE CONSTRAINTS;
DROP TABLE Exchange_T CASCADE CONSTRAINTS;
DROP TABLE K_TYPE_T CASCADE CONSTRAINTS;
DROP TABLE MEMO_T CASCADE CONSTRAINTS;
DROP TABLE PAY_T CASCADE CONSTRAINTS;
DROP TABLE PROD_T CASCADE CONSTRAINTS;
DROP TABLE TODO_T CASCADE CONSTRAINTS;
DROP TABLE USER_T CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_Exchange_T_exchange_type;
DROP SEQUENCE SEQ_HOUSE_T_KE_NO;
DROP SEQUENCE SEQ_K_TYPE_T_KE_TYPE;
DROP SEQUENCE SEQ_MEMO_T_ME_NO;
DROP SEQUENCE SEQ_PAY_T_PAY_TYPE_NO;
DROP SEQUENCE SEQ_PROD_T_PROD_TYPE;
DROP SEQUENCE SEQ_SHOP_T_SHOP_NO;
DROP SEQUENCE SEQ_TODO_T_TOD_NO;




/* Create Sequences */

CREATE SEQUENCE SEQ_Exchange_T_exchange_type INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_HOUSE_T_KE_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_K_TYPE_T_KE_TYPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_MEMO_T_ME_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PAY_T_PAY_TYPE_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_PROD_T_PROD_TYPE INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_SHOP_T_SHOP_NO INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SEQ_TODO_T_TOD_NO INCREMENT BY 1 START WITH 1;



/* Create Tables */

-- Exchange_T
CREATE TABLE Exchange_T
(
	-- exchange_type
	exchange_type number NOT NULL,
	-- exchange_Name
	exchange_Name varchar2(50 char) NOT NULL,
	-- exchange_money
	exchange_money number DEFAULT 0 NOT NULL,
	PRIMARY KEY (exchange_type)
);


-- HOUSE_T
CREATE TABLE HOUSE_T
(
	-- KE_NO
	KE_NO number NOT NULL,
	-- US_EMAIL : 이메일
	US_EMAIL varchar2(50 char) NOT NULL,
	-- ieType : 수입/지출
	-- 
	ieType number NOT NULL,
	-- KE_TYPE
	KE_TYPE number NOT NULL,
	-- KE_CONTENTS
	KE_CONTENTS varchar2(1000 char),
	-- PAY_TYPE_NO
	PAY_TYPE_NO number NOT NULL,
	-- exchange_type
	exchange_type number NOT NULL,
	-- KE_PRICE
	KE_PRICE number NOT NULL,
	-- KE_PAY_DATE
	KE_PAY_DATE date NOT NULL,
	PRIMARY KEY (KE_NO)
);


-- K_TYPE_T
CREATE TABLE K_TYPE_T
(
	-- KE_TYPE
	KE_TYPE number NOT NULL ,
	-- KE_TYPE_NAME
	KEEP_TYPE_NAME varchar2(50 char) NOT NULL,
	PRIMARY KEY (KE_TYPE)
);


-- MEMO_T
CREATE TABLE MEMO_T
(
	-- ME_NO
	ME_NO number NOT NULL,
	-- US_EMAIL : 이메일
	US_EMAIL varchar2(50 char) NOT NULL,
	-- ME_CONTENTS
	ME_CONTENTS varchar2(500 char),
	-- ME_REG_DATE
	ME_REG_DATE date NOT NULL,
	PRIMARY KEY (ME_NO)
);


-- PAY_T
CREATE TABLE PAY_T
(
	-- PAY_TYPE_NO
	PAY_TYPE_NO number NOT NULL ,
	-- PAY_NAME
	PAY_NAME varchar2(100 char) NOT NULL,
	-- US_EMAIL : 이메일
	US_EMAIL varchar2(50 char) NOT NULL,
	-- PAY_TYPE
	PAY_TYPE number NOT NULL,
	PRIMARY KEY (PAY_TYPE_NO)
);


-- PROD_T
CREATE TABLE PROD_T
(
	-- PROD_TYPE
	PROD_TYPE number NOT NULL ,
	-- PROD_T_NAME
	PROD_T_NAME varchar2(100 char) NOT NULL,
	PRIMARY KEY (PROD_TYPE)
);


-- SHOP_T
CREATE TABLE SHOP_T
(
	-- SHOP_NO
	SHOP_NO number NOT NULL,
	-- US_EMAIL : 이메일
	US_EMAIL varchar2(50 char) NOT NULL,
	-- PROD_TYPE
	PROD_TYPE number NOT NULL,
	-- SHOP_NAME
	SHOP_NAME varchar2(100 char),
	-- exchange_type
	exchange_type number NOT NULL,
	-- PRICE
	PRICE number,
	-- SHOP_REGISTER
	SHOP_REGISTER date NOT NULL,
	-- SHOP_URL
	SHOP_URL varchar2(200 char),
	-- SHOP_STATE
	SHP_STATE number NOT NULL,
	-- Buy_Date
	Buy_Date date,
	PRIMARY KEY (SHOP_NO)
);


-- TODO_T
CREATE TABLE TODO_T
(
	-- TOD_NO
	TOD_NO number NOT NULL ,
	-- US_EMAIL : 이메일
	US_EMAIL varchar2(50 char) NOT NULL,
	-- TOD_CONTENTS
	TOD_CONTENTS varchar2(3000 char),
	-- TOD_START_DATE
	TOD_START_DATE date,
	-- TOD_END_DATE
	TOD_END_DATE date,
	-- TOD_DEADLINE_DATE
	TOD_DEADLINE_DATE date,
	-- TOD_STATE
	TOD_STATE number DEFAULT 0 NOT NULL,
	-- TOD_REGDATE
	TOD_REGDATE date,
	PRIMARY KEY (TOD_NO)
);


-- 회원목록
CREATE TABLE USER_T
(
	-- US_EMAIL : 이메일
	US_EMAIL varchar2(50 char) NOT NULL ,
	-- US_PWD
	US_PWD varchar2(40 char) NOT NULL,
	-- US_FIRSTNAME
	US_FIRSTNAME varchar2(10 char) NOT NULL,
	-- US_LASTNAME
	US_LASTNAME varchar2(20 char) NOT NULL,
	-- US_SEX
	US_SEX number NOT NULL,
	-- US_REGISTERDATE
	US_REGISTERDATE date NOT NULL,
	-- US_LV
	US_LV number DEFAULT 0 NOT NULL,
	-- US_WITHDRAWAL
	US_WITHDRAWAL date,
	-- US_IMAGE : 아바타이미지
	US_IMAGE varchar2(20 char),
	-- US_PHONE
	US_PHONE varchar2(20 char),
	PRIMARY KEY (US_EMAIL)
);



/* Create Foreign Keys */

ALTER TABLE HOUSE_T
	ADD FOREIGN KEY (exchange_type)
	REFERENCES Exchange_T (exchange_type)
	ON DELETE CASCADE
;


ALTER TABLE SHOP_T
	ADD FOREIGN KEY (exchange_type)
	REFERENCES Exchange_T (exchange_type)
	ON DELETE CASCADE
;


ALTER TABLE HOUSE_T
	ADD FOREIGN KEY (KE_TYPE)
	REFERENCES K_TYPE_T (KE_TYPE)
	ON DELETE CASCADE
;


ALTER TABLE HOUSE_T
	ADD FOREIGN KEY (PAY_TYPE_NO)
	REFERENCES PAY_T (PAY_TYPE_NO)
	ON DELETE CASCADE
;


ALTER TABLE SHOP_T
	ADD FOREIGN KEY (PROD_TYPE)
	REFERENCES PROD_T (PROD_TYPE)
	ON DELETE CASCADE
;


ALTER TABLE HOUSE_T
	ADD FOREIGN KEY (US_EMAIL)
	REFERENCES USER_T (US_EMAIL)
	ON DELETE CASCADE
;


ALTER TABLE MEMO_T
	ADD FOREIGN KEY (US_EMAIL)
	REFERENCES USER_T (US_EMAIL)
	ON DELETE CASCADE
;


ALTER TABLE PAY_T
	ADD FOREIGN KEY (US_EMAIL)
	REFERENCES USER_T (US_EMAIL)
;


ALTER TABLE SHOP_T
	ADD FOREIGN KEY (US_EMAIL)
	REFERENCES USER_T (US_EMAIL)
	ON DELETE CASCADE
;


ALTER TABLE TODO_T
	ADD FOREIGN KEY (US_EMAIL)
	REFERENCES USER_T (US_EMAIL)
	ON DELETE CASCADE
;



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_Exchange_T_exchange_type BEFORE INSERT ON Exchange_T
FOR EACH ROW
BEGIN
	SELECT SEQ_Exchange_T_exchange_type.nextval
	INTO :new.exchange_type
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_HOUSE_T_KE_NO BEFORE INSERT ON HOUSE_T
FOR EACH ROW
BEGIN
	SELECT SEQ_HOUSE_T_KE_NO.nextval
	INTO :new.KE_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_K_TYPE_T_KE_TYPE BEFORE INSERT ON K_TYPE_T
FOR EACH ROW
BEGIN
	SELECT SEQ_K_TYPE_T_KE_TYPE.nextval
	INTO :new.KE_TYPE
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_MEMO_T_ME_NO BEFORE INSERT ON MEMO_T
FOR EACH ROW
BEGIN
	SELECT SEQ_MEMO_T_ME_NO.nextval
	INTO :new.ME_NO
	FROM dual;
END;

/


CREATE OR REPLACE TRIGGER TRI_PAY_T_PAY_TYPE_NO BEFORE INSERT ON PAY_T
FOR EACH ROW
BEGIN
	SELECT SEQ_PAY_T_PAY_TYPE_NO.nextval
	INTO :new.PAY_TYPE_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_PROD_T_PROD_TYPE BEFORE INSERT ON PROD_T
FOR EACH ROW
BEGIN
	SELECT SEQ_PROD_T_PROD_TYPE.nextval
	INTO :new.PROD_TYPE
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_SHOP_T_SHOP_NO BEFORE INSERT ON SHOP_T
FOR EACH ROW
BEGIN
	SELECT SEQ_SHOP_T_SHOP_NO.nextval
	INTO :new.SHOP_NO
	FROM dual;
END;

/

CREATE OR REPLACE TRIGGER TRI_TODO_T_TOD_NO BEFORE INSERT ON TODO_T
FOR EACH ROW
BEGIN
	SELECT SEQ_TODO_T_TOD_NO.nextval
	INTO :new.TOD_NO
	FROM dual;
END;

/




/* Comments */

COMMENT ON TABLE Exchange_T IS 'Exchange_T';
COMMENT ON COLUMN Exchange_T.exchange_type IS 'exchange_type';
COMMENT ON COLUMN Exchange_T.exchange_Name IS 'exchange_Name';
COMMENT ON COLUMN Exchange_T.exchange_money IS 'exchange_money';
COMMENT ON TABLE HOUSE_T IS 'HOUSE_T';
COMMENT ON COLUMN HOUSE_T.KE_NO IS 'KE_NO';
COMMENT ON COLUMN HOUSE_T.US_EMAIL IS 'US_EMAIL : 이메일';
COMMENT ON COLUMN HOUSE_T.ieType IS 'ieType : 수입/지출
';
COMMENT ON COLUMN HOUSE_T.KE_TYPE IS 'KE_TYPE';
COMMENT ON COLUMN HOUSE_T.KE_CONTENTS IS 'KE_CONTENTS';
COMMENT ON COLUMN HOUSE_T.PAY_TYPE_NO IS 'PAY_TYPE_NO';
COMMENT ON COLUMN HOUSE_T.exchange_type IS 'exchange_type';
COMMENT ON COLUMN HOUSE_T.KE_PRICE IS 'KE_PRICE';
COMMENT ON COLUMN HOUSE_T.KE_PAY_DATE IS 'KE_PAY_DATE';
COMMENT ON TABLE K_TYPE_T IS 'K_TYPE_T';
COMMENT ON COLUMN K_TYPE_T.KE_TYPE IS 'KE_TYPE';
COMMENT ON COLUMN K_TYPE_T.KEEP_TYPE_NAME IS 'KE_TYPE_NAME';
COMMENT ON TABLE MEMO_T IS 'MEMO_T';
COMMENT ON COLUMN MEMO_T.ME_NO IS 'ME_NO';
COMMENT ON COLUMN MEMO_T.US_EMAIL IS 'US_EMAIL : 이메일';
COMMENT ON COLUMN MEMO_T.ME_CONTENTS IS 'ME_CONTENTS';
COMMENT ON COLUMN MEMO_T.ME_REG_DATE IS 'ME_REG_DATE';
COMMENT ON TABLE PAY_T IS 'PAY_T';
COMMENT ON COLUMN PAY_T.PAY_TYPE_NO IS 'PAY_TYPE_NO';
COMMENT ON COLUMN PAY_T.PAY_NAME IS 'PAY_NAME';
COMMENT ON COLUMN PAY_T.US_EMAIL IS 'US_EMAIL : 이메일';
COMMENT ON COLUMN PAY_T.PAY_TYPE IS 'PAY_TYPE';
COMMENT ON TABLE PROD_T IS 'PROD_T';
COMMENT ON COLUMN PROD_T.PROD_TYPE IS 'PROD_TYPE';
COMMENT ON COLUMN PROD_T.PROD_T_NAME IS 'PROD_T_NAME';
COMMENT ON TABLE SHOP_T IS 'SHOP_T';
COMMENT ON COLUMN SHOP_T.SHOP_NO IS 'SHOP_NO';
COMMENT ON COLUMN SHOP_T.US_EMAIL IS 'US_EMAIL : 이메일';
COMMENT ON COLUMN SHOP_T.PROD_TYPE IS 'PROD_TYPE';
COMMENT ON COLUMN SHOP_T.SHOP_NAME IS 'SHOP_NAME';
COMMENT ON COLUMN SHOP_T.exchange_type IS 'exchange_type';
COMMENT ON COLUMN SHOP_T.PRICE IS 'PRICE';
COMMENT ON COLUMN SHOP_T.SHOP_REGISTER IS 'SHOP_REGISTER';
COMMENT ON COLUMN SHOP_T.SHOP_URL IS 'SHOP_URL';
COMMENT ON COLUMN SHOP_T.SHP_STATE IS 'SHOP_STATE';
COMMENT ON COLUMN SHOP_T.Buy_Date IS 'Buy_Date';
COMMENT ON TABLE TODO_T IS 'TODO_T';
COMMENT ON COLUMN TODO_T.TOD_NO IS 'TOD_NO';
COMMENT ON COLUMN TODO_T.US_EMAIL IS 'US_EMAIL : 이메일';
COMMENT ON COLUMN TODO_T.TOD_CONTENTS IS 'TOD_CONTENTS';
COMMENT ON COLUMN TODO_T.TOD_START_DATE IS 'TOD_START_DATE';
COMMENT ON COLUMN TODO_T.TOD_END_DATE IS 'TOD_END_DATE';
COMMENT ON COLUMN TODO_T.TOD_DEADLINE_DATE IS 'TOD_DEADLINE_DATE';
COMMENT ON COLUMN TODO_T.TOD_STATE IS 'TOD_STATE';
COMMENT ON COLUMN TODO_T.TOD_REGDATE IS 'TOD_REGDATE';
COMMENT ON TABLE USER_T IS '회원목록';
COMMENT ON COLUMN USER_T.US_EMAIL IS 'US_EMAIL : 이메일';
COMMENT ON COLUMN USER_T.US_PWD IS 'US_PWD';
COMMENT ON COLUMN USER_T.US_FIRSTNAME IS 'US_FIRSTNAME';
COMMENT ON COLUMN USER_T.US_LASTNAME IS 'US_LASTNAME';
COMMENT ON COLUMN USER_T.US_SEX IS 'US_SEX';
COMMENT ON COLUMN USER_T.US_REGISTERDATE IS 'US_REGISTERDATE';
COMMENT ON COLUMN USER_T.US_LV IS 'US_LV';
COMMENT ON COLUMN USER_T.US_WITHDRAWAL IS 'US_WITHDRAWAL';
COMMENT ON COLUMN USER_T.US_IMAGE IS 'US_IMAGE : 아바타이미지';
COMMENT ON COLUMN USER_T.US_PHONE IS 'US_PHONE';



